version: '3.5'

services:
  jupyter:
    image: jupyter/datascience-notebook
    ports:
      - "8889:8888"
    volumes:
      - "jupyter_data:/home/jovyan/work"
      - "./jupyter_data/Untitled.ipynb:/home/jovyan/work/Untitled.ipynb"
      - "./jupyter_data/historico:/home/jovyan/work/historico"
    env_file:
      - jupyter.env
  nodered:
    image: nodered/node-red:1.3.5
    ports:
      - "1880:1880"
    volumes:
      - "nodered_data:/data"
    env_file:
      - nodered.env
  influx:
    image: influxdb:2.0
    ports:
      - "8086:8086"
    env_file:
      - influx.env
    volumes:
      - "influx_data:/var/lib/influxdb2"
  grafana:
    image: grafana/grafana:7.5.7
    ports:
      - "3000:3000"
    env_file:
      - grafana.env

volumes:
  jupyter_data:
  influx_data:
  nodered_data: